env:
  es2021: true
  node: true
extends:
  - google
  - standard-with-typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ["./tsconfig.json"]
plugins:
  - "@typescript-eslint"
rules:
  {
    "max-len":
      [
        "error",
        {
          "ignoreComments": true,
          "ignoreStrings": true,
          "ignoreTemplateLiterals": true,
        },
      ],
    "no-invalid-this": 0,
    "new-cap": 0,
    "template-curly-spacing": ["error", "always"],
    "object-curly-spacing": ["error", "always"],
    "object-curly-newline":
      [
        "error",
        {
          "ImportDeclaration": { "multiline": true, "minProperties": 3 },
          "ObjectExpression": "always",
          "ObjectPattern": { "multiline": true },
        },
      ],
    "object-property-newline":
      ["error", { "allowAllPropertiesOnSameLine": false }],
    "newline-per-chained-call": ["error", { "ignoreChainWithDepth": 2 }],
    "@typescript-eslint/semi": ["error", "always"],
    "function-paren-newline": ["error", { "minItems": 2 }],
  }
